<?php $_code = $this->getMethodCode(); ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li class="form-alt"><?php echo $this->getRedirectMessage() ?></li>
    <li>
	<input type="checkbox" id="<?php echo $_code ?>_one_click_payment" name="payment[<?php echo $_code; ?>][one_click_payment]" title="<?php echo $this->__('One Click Payment') ?>" value="true" style="margin-top: -4px;" />
        <label for="<?php echo $_code ?>_one_click_payment" class="required" style="float: none;"><?php echo $this->__('One Click Payment') ?></label>
    </li>
</ul>